apiVersion: v1
kind: ReplicationController
metadata:
  name: url-shortener
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: golgothlt/url_shortener
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
